package club.plutomc.plutoproject.apiutils.color

// Latte
const val LATTE_ROSEWATER = "#dc8a78"
const val LATTE_FLAMINGO = "#dd7878"
const val LATTE_PINK = "#ea76cb"
const val LATTE_MAUVE = "#8839ef"
const val LATTE_RED = "#d20f39"
const val LATTE_MAROON = "#e64553"
const val LATTE_PEACH = "#fe640b"
const val LATTE_YELLOW = "#df8e1d"
const val LATTE_GREEN = "#40a02b"
const val LATTE_TEAL = "#179299"
const val LATTE_SKY = "#04a5e5"
const val LATTE_BLUE = "#1e66f5"
const val LATTE_LAVENDER = "#7287fd"
const val LATTE_TEXT = "#4c4f69"
const val LATTE_SUBTEXT_1 = "#5c5f77"
const val LATTE_SUBTEXT_0 = "#6c6f85"
const val LATTE_OVERLAY_2 = "#7c7f93"
const val LATTE_OVERLAY_1 = "#8c8fa1"
const val LATTE_OVERLAY_0 = "#9ca0b0"
const val LATTE_SURFACE_2 = "#acb0be"
const val LATTE_SURFACE_1 = "#bcc0cc"
const val LATTE_SURFACE_0 = "#ccd0da"
const val LATTE_BASE = "#eff1f5"
const val LATTE_MANTLE = "#e6e9ef"
const val LATTE_CRUST = "#dce0e8"

// Frappe
const val FRAPPE_ROSEWATER = "#f2d5cf"
const val FRAPPE_FLAMINGO = "#eebebe"
const val FRAPPE_PINK = "#f4b8e4"
const val FRAPPE_MAUVE = "#ca9ee6"
const val FRAPPE_RED = "#e78284"
const val FRAPPE_MAROON = "#ea999c"
const val FRAPPE_PEACH = "#ef9f76"
const val FRAPPE_YELLOW = "#e5c890"
const val FRAPPE_GREEN = "#a6d189"
const val FRAPPE_TEAL = "#81c8be"
const val FRAPPE_SKY = "#99d1db"
const val FRAPPE_SAPPHIRE = "#85c1dc"
const val FRAPPE_BLUE = "#8caaee"
const val FRAPPE_LAVENDER = "#babbf1"
const val FRAPPE_TEXT = "#c6d0f5"
const val FRAPPE_SUBTEXT_1 = "#b5bfe2"
const val FRAPPE_SUBTEXT_0 = "#a5adce"
const val FRAPPE_OVERLAY_2 = "#949cbb"
const val FRAPPE_OVERLAY_1 = "#838ba7"
const val FRAPPE_OVERLAY_0 = "#737994"
const val FRAPPE_SURFACE_2 = "#626880"
const val FRAPPE_SURFACE_1 = "#51576d"
const val FRAPPE_SURFACE_0 = "#414559"
const val FRAPPE_BASE = "#303446"
const val FRAPPE_MANTLE = "#292c3c"
const val FRAPPE_CRUST = "#232634"

// Macchiato
const val MACCHIATO_ROSEWATER = "#f4dbd6"
const val MACCHIATO_FLAMINGO = "#f0c6c6"
const val MACCHIATO_PINK = "#f5bde6"
const val MACCHIATO_MAUVE = "#c6a0f6"
const val MACCHIATO_RED = "#ed8796"
const val MACCHIATO_MAROON = "#ee99a0"
const val MACCHIATO_PEACH = "#f5a97f"
const val MACCHIATO_YELLOW = "#eed49f"
const val MACCHIATO_GREEN = "#a6da95"
const val MACCHIATO_TEAL = "#8bd5ca"
const val MACCHIATO_SKY = "#91d7e3"
const val MACCHIATO_SAPPHIRE = "#7dc4e4"
const val MACCHIATO_BLUE = "#8aadf4"
const val MACCHIATO_LAVENDER = "#b7bdf8"
const val MACCHIATO_TEXT = "#cad3f5"
const val MACCHIATO_SUBTEXT_1 = "#b8c0e0"
const val MACCHIATO_SUBTEXT_0 = "#a5adcb"
const val MACCHIATO_OVERLAY_2 = "#939ab7"
const val MACCHIATO_OVERLAY_1 = "#8087a2"
const val MACCHIATO_OVERLAY_0 = "#6e738d"
const val MACCHIATO_SURFACE_2 = "#5b6078"
const val MACCHIATO_SURFACE_1 = "#494d64"
const val MACCHIATO_SURFACE_0 = "#363a4f"
const val MACCHIATO_BASE = "#24273a"
const val MACCHIATO_MANTLE = "#1e2030"
const val MACCHIATO_CRUST = "#181926"

// Mocha
const val MOCHA_ROSEWATER = "#f5e0dc"
const val MOCHA_FLAMINGO = "#f2cdcd"
const val MOCHA_PINK = "#f5c2e7"
const val MOCHA_MAUVE = "#cba6f7"
const val MOCHA_RED = "#f38ba8"
const val MOCHA_MAROON = "#eba0ac"
const val MOCHA_PEACH = "#fab387"
const val MOCHA_YELLOW = "#f9e2af"
const val MOCHA_GREEN = "#a6e3a1"
const val MOCHA_TEAL = "#94e2d5"
const val MOCHA_SKY = "#89dceb"
const val MOCHA_SAPPHIRE = "#74c7ec"
const val MOCHA_BLUE = "#89b4fa"
const val MOCHA_LAVENDER = "#b4befe"
const val MOCHA_TEXT = "#cdd6f4"
const val MOCHA_SUBTEXT_1 = "#bac2de"
const val MOCHA_SUBTEXT_0 = "#a6adc8"
const val MOCHA_OVERLAY_2 = "#9399b2"
const val MOCHA_OVERLAY_1 = "#7f849c"
const val MOCHA_OVERLAY_0 = "#6c7086"
const val MOCHA_SURFACE_2 = "#585b70"
const val MOCHA_SURFACE_1 = "#45475a"
const val MOCHA_SURFACE_0 = "#313244"
const val MOCHA_BASE = "#1e1e2e"
const val MOCHA_MANTLE = "#181825"
const val MOCHA_CRUST = "#11111b"

@Suppress("unused")
object Catppuccin {

    object LATTE {
        const val ROSEWATER = "#dc8a78"
        const val FLAMINGO = "#dd7878"
        const val PINK = "#ea76cb"
        const val MAUVE = "#8839ef"
        const val RED = "#d20f39"
        const val MAROON = "#e64553"
        const val PEACH = "#fe640b"
        const val YELLOW = "#df8e1d"
        const val GREEN = "#40a02b"
        const val TEAL = "#179299"
        const val SKY = "#04a5e5"
        const val BLUE = "#1e66f5"
        const val LAVENDER = "#7287fd"
        const val TEXT = "#4c4f69"
        const val SUBTEXT_1 = "#5c5f77"
        const val SUBTEXT_0 = "#6c6f85"
        const val OVERLAY_2 = "#7c7f93"
        const val OVERLAY_1 = "#8c8fa1"
        const val OVERLAY_0 = "#9ca0b0"
        const val SURFACE_2 = "#acb0be"
        const val SURFACE_1 = "#bcc0cc"
        const val SURFACE_0 = "#ccd0da"
        const val BASE = "#eff1f5"
        const val MANTLE = "#e6e9ef"
        const val CRUST = "#dce0e8"
    }

    object FRAPPE {
        const val ROSEWATER = "#f2d5cf"
        const val FLAMINGO = "#eebebe"
        const val PINK = "#f4b8e4"
        const val MAUVE = "#ca9ee6"
        const val RED = "#e78284"
        const val MAROON = "#ea999c"
        const val PEACH = "#ef9f76"
        const val YELLOW = "#e5c890"
        const val GREEN = "#a6d189"
        const val TEAL = "#81c8be"
        const val SKY = "#99d1db"
        const val SAPPHIRE = "#85c1dc"
        const val BLUE = "#8caaee"
        const val LAVENDER = "#babbf1"
        const val TEXT = "#c6d0f5"
        const val SUBTEXT_1 = "#b5bfe2"
        const val SUBTEXT_0 = "#a5adce"
        const val OVERLAY_2 = "#949cbb"
        const val OVERLAY_1 = "#838ba7"
        const val OVERLAY_0 = "#737994"
        const val SURFACE_2 = "#626880"
        const val SURFACE_1 = "#51576d"
        const val SURFACE_0 = "#414559"
        const val BASE = "#303446"
        const val MANTLE = "#292c3c"
        const val CRUST = "#232634"
    }

    object MACCHIATO {
        const val ROSEWATER = "#f4dbd6"
        const val FLAMINGO = "#f0c6c6"
        const val PINK = "#f5bde6"
        const val MAUVE = "#c6a0f6"
        const val RED = "#ed8796"
        const val MAROON = "#ee99a0"
        const val PEACH = "#f5a97f"
        const val YELLOW = "#eed49f"
        const val GREEN = "#a6da95"
        const val TEAL = "#8bd5ca"
        const val SKY = "#91d7e3"
        const val SAPPHIRE = "#7dc4e4"
        const val BLUE = "#8aadf4"
        const val LAVENDER = "#b7bdf8"
        const val TEXT = "#cad3f5"
        const val SUBTEXT_1 = "#b8c0e0"
        const val SUBTEXT_0 = "#a5adcb"
        const val OVERLAY_2 = "#939ab7"
        const val OVERLAY_1 = "#8087a2"
        const val OVERLAY_0 = "#6e738d"
        const val SURFACE_2 = "#5b6078"
        const val SURFACE_1 = "#494d64"
        const val SURFACE_0 = "#363a4f"
        const val BASE = "#24273a"
        const val MANTLE = "#1e2030"
        const val CRUST = "#181926"
    }

    object MOCHA {
        const val ROSEWATER = "#f5e0dc"
        const val FLAMINGO = "#f2cdcd"
        const val PINK = "#f5c2e7"
        const val MAUVE = "#cba6f7"
        const val RED = "#f38ba8"
        const val MAROON = "#eba0ac"
        const val PEACH = "#fab387"
        const val YELLOW = "#f9e2af"
        const val GREEN = "#a6e3a1"
        const val TEAL = "#94e2d5"
        const val SKY = "#89dceb"
        const val SAPPHIRE = "#74c7ec"
        const val BLUE = "#89b4fa"
        const val LAVENDER = "#b4befe"
        const val TEXT = "#cdd6f4"
        const val SUBTEXT_1 = "#bac2de"
        const val SUBTEXT_0 = "#a6adc8"
        const val OVERLAY_2 = "#9399b2"
        const val OVERLAY_1 = "#7f849c"
        const val OVERLAY_0 = "#6c7086"
        const val SURFACE_2 = "#585b70"
        const val SURFACE_1 = "#45475a"
        const val SURFACE_0 = "#313244"
        const val BASE = "#1e1e2e"
        const val MANTLE = "#181825"
        const val CRUST = "#11111b"
    }

}