main: club.plutomc.plutoproject.common.connector.plugin.bukkit.BukkitConnectorPlugin
name: pluto-connector
version: 3.0.0-SNAPSHOT
api-version: 1.13
authors:
  - nostalfinals
  - Members of PlutoProject