main: club.plutomc.plutoproject.messaging.plugin.BukkitMessagingPlugin
name: pluto-redis-messaging
version: 3.0.0-SNAPSHOT
api-version: 1.20
depend:
  - pluto-connector
authors:
  - nostalfinals
  - Members of PlutoProject